node('master') {

  stage('Preparation') {
    git 'https://github.com/jglick/simple-maven-project-with-tests.git'
  }

  stage('Build') {
    withMaven {
        sh label: '', script: 'mvn -Dmaven.test.failure.ignore clean package'
    }
  }
  
}
